stripe.settings:
  type: config_object
  label: 'VotingApi settings'
  mapping:
    environment:
      type: string
      label: 'Test or live environment'
    apikey:
      type: mapping
      label: 'API keys'
      mapping:
        test:
          type: mapping
          label: 'Test keys'
          mapping:
            public:
              type: string
              label: Public key
            secret:
              type: string
              label: Private key
            webhook:
              type: string
              label: Webhook
        live:
          type: mapping
          label: 'Live keys'
          mapping:
            public:
              type: string
              label: Public key
            secret:
              type: string
              label: Private key
            webhook:
              type: string
              label: Webhook
